services:
  server:
    build:
      context: .
      target: development
    image: react-app-server:development
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
        - action: rebuild
          path: Dockerfile
        - action: rebuild
          path: compose.yml
