services:
  web:
    depends_on: 
      - api
    build:
      context: ./web
      target: development
    image: vidly-web:development
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./web
          target: /app
          ignore:
            - ./web/node_modules/
        - action: rebuild
          path: ./web/package.json
        - action: rebuild
          path: ./web/Dockerfile
        - action: rebuild
          path: compose.dev.yml

  api:
    depends_on: 
      - db
    build:
      context: ./api
      target: development
    image: vidly-api:development
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    develop:
      watch:
        - action: sync
          path: ./api
          target: /app
          ignore:
            - ./api/node_modules/
        - action: rebuild
          path: ./api/package.json
        - action: rebuild
          path: ./api/Dockerfile
        - action: rebuild
          path: ./api/migrations/
        - action: rebuild
          path: compose.dev.yml

  db:
    image: mongo:6.0.13-jammy
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
