x-deploy: &deploy
  deploy:
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s

services:
  web:
    depends_on: 
      - api
    build:
      context: ./web
      target: production
    image: ammarshah/vidly-web:latest
    ports:
      - 80:8080
    <<: *deploy

  api:
    depends_on: 
      - db
    build:
      context: ./api
      target: production
    image: ammarshah/vidly-api:latest
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://db/vidly
    <<: *deploy

  db:
    image: mongo:6.0.13-jammy
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
    <<: *deploy

volumes:
  vidly:
